### ISSUE TITLE
The floral color

### ISSUE THREAD

**Issue by markendley** [SmackBang/ednco#2]
Did I pick the right color breakdown?

**Comment by markendley** [comment]
Hey Flick, could you send me the hexagonal breakdown for this color

**Comment by felicitymchugh** [comment]
#6affcc

**Comment by markendley** [comment]
Are you sure about that color?
It's different to the color on their current site?
http://www.edwardsandco.com.au/

I've updated it anyway

**Comment by markendley** [comment]
I'll just close this issue, we can reopen it later
