### ISSUE TITLE
Stylists - Social Media

### ISSUE THREAD

**Issue by felicitymchugh** [SmackBang/ednco#30]
Can we please add a 'personal website' icon (just a little computer please) to show up and also add 'youtube' field / icon?

**Comment by renzo-cast2** [comment]
Hi Felicity,

I'm taking care of this issue. Could you design these icons for me and supply them as vectors?

**Comment by felicitymchugh** [comment]
Hey!
Here they are :)


[Vectors.zip](https://github.com/SmackBang/ednco/files/237953/Vectors.zip)

**Comment by renzo-cast2** [comment]
Mark, I have added the images to the assets folder and updated the code. 
Can you fix the svg files.
