### ISSUE TITLE
FAQ page

### ISSUE THREAD

**Issue by felicitymchugh** [SmackBang/ednco#35]
Please add FAQ page 
PSD is on dropbox + content in email

**Comment by markendley** [comment]
Hey Laurence,

If you grab the latest db from the staging site, you'll find that all the custom fields have been generated, and all the data has been inputted, so all you gotta do is output it.

Create a template called page-faqs.php and then you'll find there is some code that you can re-use on the Education page (where it says "Upcoming Events", the CSS and JS for the collapses have already been made.

In the end, you'll just be copy/pasting some code and then doing a bit of revision on how to output those custom fields with php!



This is what the FAQ page should look like when your done.
![edwardsandco-faq](https://cloud.githubusercontent.com/assets/6570606/14941646/632bff2a-0fe6-11e6-91e9-79c50b6900e4.jpg)


This is the education page, and you can see the collapses have already been built,
![screen shot 2016-05-01 at 9 48 23 pm](https://cloud.githubusercontent.com/assets/6570606/14941651/aa11d824-0fe6-11e6-9994-0da75f199051.png)

**Comment by renzo-cast** [comment]
Done Mark. 
One question, the education has the '-' bullet for collapsed and '+' for open. In the FAQ page example above it is the opposite. 
Would you like me to reverse the bullets for the FAQ page (as shown in the page example above)?

**Comment by renzo-cast** [comment]
Also - I'm not able to change the Assignee for this.

**Comment by markendley** [comment]
All good - thanks!
